name: CI Pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run electron:build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VTKounter.AppImage
          path: dist_electron/VTKounter-*.AppImage
          retention-days: 5